import Head from 'next/head'
import { BsFillMoonStarsFill } from "react-icons/bs"
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import sharon from '../public/sharr.png'
import aboutme from '../public/aboutme.png'
import css from '../public/css.png'
import html from '../public/html.png'
import git from '../public/git.png'
import Uiux from '../public/ui.png'
import reactlogo from '../public/react.png'
import boots from '../public/bootstrap.png'
import jslogo from '../public/jslogo.png'
import tailwindlogo from '../public/tailwindcss.png'
import zana from '../public/zana.png'
import weatherapp from '../public/weatherapp.JPEG'
import metaverse from '../public/metaverse.jpg'
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Falomo Sharon portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-5 flex justify-between'>
            <h1 className='text-xl font-libre dark:text-white'>Sharon <span className="text-cyan-300">Portfolio </span> </h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white' />
              </li>
              <li><a className='bg-cyan-400 text-white px-4 py-2 rounded-lg ml-8' href='https://falomosharon.hashnode.dev/getting-started-in-technical-writing' target="_blank">Blog</a></li>
            </ul>
          </nav>
          <div className='text-center px-10 pb-10'>
            <h2 className='text-5xl py-2 text-cyan-500 font-medium  md:text-6xl '>Falomo Sharon</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-slate-100'>Frontend Developer/Technical Writer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl mas-w-xl mx-auto dark:text-slate-200'>
              My passion lies in making the interface not only creative and aesthetic but also really functional for a good user experience and solving problems.
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href='https://twitter.com/sharonfalomo?s=11&t=u5By12KDfWxoH722yIJ3FQ' target="_blank"> <AiFillTwitterCircle className='hover:text-cyan-400 hover:font-medium active:text-blue-900' /></a>
            <a href='http://linkedin.com/in/sharon-falomo' target="_blank"><AiFillLinkedin className='hover:text-cyan-400 hover:font-medium active:text-blue-900' /></a>
            <a href="https://github.com/falsharion" target="_blank"><AiFillGithub className='hover:text-cyan-400 hover:font-medium active:text-blue-900' /></a>
          </div>
          <div className='relative my-10 mx-auto bg-gradient-to-b from-cyan-500 rounded-full overflow-hidden w-80 h-80 md:h-96 md:w-96'>
            <Image
              src={sharon}
              fill
              sizes="100vw"
              style={{
                objectFit: "cover"
              }} />
          </div>
        </section>
        {/* end of hero section */}
        {/* about me section start*/}
        <section>
          <div>
            <h3 className='text-3xl py-8 dark:text-slate-200'>
              About me
            </h3>
            <div className='sm:flex py-4 pr-4'>
              <div>
                <p className='text-md py-2 leading-8 max-w-sm text-gray-800 dark:text-gray-500'>
                  My name is Falomo Sharon Simisola. I am Nigerian. I am a Frontend developer who <span className="text-cyan-300">links together the world of design and technology</span> for users to interact with using the appropriate frontend techniques.
                </p>

                <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-500'>
                  While not coding or learning, I enjoy watching movies, making graphic drawings, making tech content for my tiktok and spending time with friends and family
                </p>
              </div>
              <div>
                <Image
                  src={aboutme}
                  className='rounded-lg object-cover'
                  width={'50%'}
                  height={"50%"}
                  alt = "me"
                  layout={"responsive"}
                  style={{
                    maxWidth: "100%",
                    height: "auto"
                  }} />
              </div>
            </div>
          </div>
         
        </section>
         {/* about me section end */}
         {/* Skills section starts */}
        <section>
          <h3 className='text-3xl py-8 dark:text-slate-200'>
            My Skills
          </h3>
          <div className='lg:grid gap-3 grid-cols-2'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-300/20 flex-1'>
              <Image
                src={html}
                width={100}
                height={100}
                alt = "me"
                className="inline"
                style={{
                  maxWidth: "100%",
                  height: "auto"
                }} />
              <h3 className='text-lg text-cyan-500 font-medium pt-8 pb-2'>HTML</h3>
              <div className="w-full bg-gray-200 rounded-full">
                <div className="bg-cyan-500 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-l-full" style={{ width: `98%` }}> 98%</div>
              </div>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-300/20 flex-1'>
              <Image
                src={css}
                width={100}
                height={100}
                alt = "me"
                className="inline"
                style={{
                  maxWidth: "100%",
                  height: "auto"
                }} />
              <h3 className='text-lg text-cyan-500  font-medium pt-8 pb-2'>CSS</h3>
              <div className="w-full bg-gray-200 rounded-full">
                <div className="bg-cyan-500 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-l-full" style={{ width: `90%` }}> 90%</div>
              </div></div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-300/20 flex-1'>
              <Image
                src={jslogo}
                width={100}
                alt = "me"
                height={100}
                className="inline"
                style={{
                  maxWidth: "100%",
                  height: "auto"
                }} />
              <h3 className='text-lg text-cyan-500 font-medium pt-8 pb-2'>JAVASCRIPT</h3>
              <div className="w-full bg-gray-200 rounded-full">
                <div className="bg-cyan-500 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-l-full" style={{ width: `80%` }}> 80%</div>
              </div></div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-300/20 flex-1'>
              <Image
                src={reactlogo}
                width={100}
                height={100}
                alt = "me"
                className="inline"
                style={{
                  maxWidth: "100%",
                  height: "auto"
                }} />
              <h3 className='text-lg text-cyan-500 font-medium pt-8 pb-2'>REACT</h3>
              <div className="w-full bg-gray-200 rounded-full">
                <div className="bg-cyan-500 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-l-full" style={{ width: `69%` }}> 69%</div>
              </div></div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-300/20 flex-1'>
              <Image
                src={boots}
                width={100}
                alt = "me"
                height={100}
                className="inline"
                style={{
                  maxWidth: "100%",
                  height: "auto"
                }} />
              <h3 className='text-lg text-cyan-500 font-medium pt-8 pb-2'>BOOTSTRAP</h3>
              <div className="w-full bg-gray-200 rounded-full">
                <div className="bg-cyan-500 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-l-full" style={{ width: `78%` }}> 78%</div>
              </div></div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-300/20 flex-1'>
              <Image
                src={tailwindlogo}
                width={100}
                alt = "me"
                height={100}
                className="inline"
                style={{
                  maxWidth: "100%",
                  height: "auto"
                }} />
              <h3 className='text-lg text-cyan-500  font-medium pt-8 pb-2'>TAILWINDCSS</h3>
              <div className="w-full bg-gray-200 rounded-full">
                <div className="bg-cyan-500 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-l-full" style={{ width: `87%` }}> 87%</div>
              </div></div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-300/20 flex-1'>
              <Image
                src={git}
                width={100}
                alt = "me"
                height={100}
                className="inline"
                style={{
                  maxWidth: "100%",
                  height: "auto"
                }} />
              <h3 className='text-lg text-cyan-500  font-medium pt-8 pb-2'>GIT</h3>
              <div className="w-full bg-gray-200 rounded-full">
                <div className="bg-cyan-500 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-l-full" style={{ width: `92%` }}> 92%</div>
              </div></div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-300/20 flex-1'>
              <Image
                src={Uiux}
                width={100}
                alt = "me"
                height={100}
                className="inline dark:bg-cyan-200 rounded"
                style={{
                  maxWidth: "100%",
                  height: "auto"
                }} />
              <h3 className='text-lg text-cyan-500  font-medium pt-8 pb-2'>UI/UX</h3>
              <div className="w-full bg-gray-200 rounded-full">
                <div className="bg-cyan-500 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-l-full" style={{ width: `75%` }}> 75%</div>
              </div></div>

          </div>
        </section>
        {/* skills section ends */}
        {/* project section starts */}
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-slate-100'>Projects</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-500'>
            These are some of my best responsive projects i've worked on so far with the knowledge i've acquired. More projects will be added.
            </p>

          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image
                src={zana}
                className='rounded-lg object-cover'
                width={'100%'}
                alt = "me"
                height={"100%"}
                layout={"responsive"}
                style={{
                  maxWidth: "100%",
                  height: "auto"
                }} />
              <h4 className='text-cyan-500 dark:text-slate-100'>ZANA FASHION STORE</h4>
              <a href='https://zanafashionstore.netlify.app/' target="_blank" className='dark:text-slate-100/70'>Live Demo</a>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                src={weatherapp}
                className='rounded-lg object-cover'
                width={'100%'}
                alt = "me"
                height={"100%"}
                layout={"responsive"}
                style={{
                  maxWidth: "100%",
                  height: "auto"
                }} />
              <h4 className='text-cyan-500 dark:text-slate-100'>WEATHER APP</h4>
              <a href='https://falsharion.github.io/weather-app/'  target="_blank" className='dark:text-slate-100/70'>Live Demo</a>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image
                src={metaverse}
                className='rounded-lg object-cover'
                width={'100%'}
                alt = "me"
                height={"100%"}
                layout={"responsive"}
                style={{
                  maxWidth: "100%",
                  height: "auto"
                }} />
              <h4 className='text-cyan-500 dark:text-slate-100'>METAVERSE</h4>
              <a href='https://falsharion.github.io/tailwindPractice/' target="_blank" className='dark:text-slate-100/70'>Live Demo</a>
            </div>
          </div>
        </section>
      </main>
      <footer className="footer p-10 bg-gray-900 text-neutral-content">
  <div className='pb-6'>
  <h3 className='text-xl font-libre text-white'>Sharon <span className="text-cyan-300">Portfolio </span> </h3>
    <p className='text-slate-300 '>falomosharl@gmail.com</p>
  </div> 
  <div>
    <div className="grid grid-flow-col gap-4">
    <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href='https://twitter.com/sharonfalomo?s=11&t=u5By12KDfWxoH722yIJ3FQ' target="_blank"> <AiFillTwitterCircle className='hover:text-cyan-400 hover:font-medium active:text-blue-900' /></a>
            <a href='http://linkedin.com/in/sharon-falomo' target="_blank"><AiFillLinkedin className='hover:text-cyan-400 hover:font-medium active:text-blue-900' /></a>
            <a href="https://github.com/falsharion" target="_blank"><AiFillGithub className='hover:text-cyan-400 hover:font-medium active:text-blue-900' /></a>
          </div>
    </div>
  </div>
</footer>
    </div>
  );
}
